url: http://jclouds.apache.org
title: Apache jclouds
markdown: rdiscount
pygments: true
paginate: 5
paginate_path: "blog/page:num"
permalink: pretty
#permalink: /blog/:categories/:year/:month/:day/:title